GET http://localhost:18080/restvoting/rest/votes
//GET http://localhost:18080/restvoting/rest/votes/2019-01-29
Accept: */*
Content-Type: application/json
Cache-Control: no-cache
Authorization: Basic YWRtaW5AZ21haWwuY29tOmFkbWlu

###