POST http://localhost:18080/restvoting/rest/admin/dishes/add/many/100014
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Basic YWRtaW5AZ21haWwuY29tOmFkbWlu

[{"date":"2018-12-15T09:00","description":"Рубленая Котлета","price":"abc"}, {"date":"2018-12-15T09:00",
  "description":"Солянка1","price":"ert"}]

###



