POST http://localhost:18080/restvoting/rest/admin/dishes/add/many/100014
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Basic YWRtaW5AZ21haWwuY29tOmFkbWlu

[{"dateTime":"2018-12-15T09:00","description":"Котлета1","price":100.00}, {"dateTime":"2018-12-15T09:00",
  "description":"Солянка1","price":150.70}]

###



