# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
POST http://localhost:18080/restvoting/rest/admin/dishes/add/100003
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: Basic YWRtaW5AZ21haWwuY29tOmFkbWlu

{"date":"2018-12-15T09:00","description":"Рубленая Котлета","price":"abc"}

###
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);